### ISSUE TITLE
load-balancing

### ISSUE THREAD

**Issue by Semior001** [Semior001/groxy#8]
allow user to introduce several upstreams for a match, e.g.:
```yaml
  - match:
      uri: "com.github.Semior001.groxy.example.mock..Upstream/Get"
    forward:
      upstreams:
        - example-1
        - example-1-replica
      load-balancing: round-robin
```

remove the "upstream" field from the config, consumers now must specify **a list** of upstreams, optionally setting the load balancing policy, default is round-robin
